{% set name = "radiosphere" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radioSphere-{{ version }}.tar.gz
  sha256: e4f8a600dcbed4a401f61b86f3cdfe66fd8fda98fdbf4d6eafdaf9016f59135f

build:
  entry_points:
    - calibrateManyParticles = radioSphere.scripts.calibrateManyParticles:main
    - calibrateSingleParticle = radioSphere.scripts.calibrateSingleParticle:main
    - findParticles = radioSphere.scripts.findParticles:main
    - optimiseParticles = radioSphere.scripts.optimiseParticles:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=40.6.0
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - scikit-image
    - ipython
    - tifffile
    - matplotlib-base
    - tqdm
    - notebook
    - json5
    - numba

test:
  imports:
    - radiosphere
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://ttk.gricad-gitlab.univ-grenoble-alpes.fr/ttk/radioSphere"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.md
  summary: "Single-projection reconstruction technique for positioning monodisperse spheres in 3D with a divergent x-ray beam"
  doc_url: https://ttk.gricad-pages.univ-grenoble-alpes.fr/radioSphere/

extra:
  recipe-maintainers:
    - benjym
